name: Daily arXiv Update

on:
  schedule:
    - cron: '0 12 * * 0,3'  # 周日与周三 UTC 时间 12:00 运行
  workflow_dispatch:     # 允许手动触发

permissions:
  contents: write
  issues: write 

jobs:
  update-papers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch arXiv papers
        run: |
          python main.py

      # - name: Commit and push changes
      #   run: |
      #     git config --global user.name "Yongqi Huang"
      #     git config --global user.email "yqhuang@tju.edu.cn"
      #     git add README.md
      #     git commit -m "Update arXiv papers"
      #     git push
      - name: Commit and push changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: '✏️ Update papers automatically.'
          force-add: 'true'
          files: README.md .github/ISSUE_TEMPLATE.md
          name: Yongqi Huang
          email:shanlz2119@tju.edu.cn

      - name: Create an issue to notify
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
