name: Daily arXiv Update

on:
  schedule:
    - cron: '0 12 * * *'  # 每天 UTC 时间 8:00 运行
  workflow_dispatch:     # 允许手动触发

jobs:
  update-papers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch arXiv papers
        run: |
          python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Yongqi Huang"
          git config --global user.email "yqhuang@tju.edu.cn"
          git add README.md
          git commit -m "Update arXiv papers"
          git push
